"""empty message

Revision ID: 13ed88965125
Revises: 50c96a4aaba0
Create Date: 2014-03-23 12:36:21.197294

"""

# revision identifiers, used by Alembic.
revision = '13ed88965125'
down_revision = '50c96a4aaba0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
