"""empty message

Revision ID: 1720dbe600b7
Revises: 13ed88965125
Create Date: 2014-03-23 12:38:21.719088

"""

# revision identifiers, used by Alembic.
revision = '1720dbe600b7'
down_revision = '13ed88965125'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
