"""empty message

Revision ID: 2c3770e31104
Revises: 45bf06099bb7
Create Date: 2014-03-13 20:04:27.591518

"""

# revision identifiers, used by Alembic.
revision = '2c3770e31104'
down_revision = '45bf06099bb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
