"""empty message

Revision ID: 353f617f311
Revises: None
Create Date: 2014-03-04 10:38:36.686093

"""

# revision identifiers, used by Alembic.
revision = '353f617f311'
down_revision = None

from alembic import op
import sqlalchemy as sa
# from ../../pintube/__init__ import db
from sqlalchemy.types import TypeDecorator, VARCHAR
from sqlalchemy.ext.mutable import Mutable
import json


class JSONEncodedDict(TypeDecorator):
    "Represents an immutable structure as a json-encoded string."

    impl = VARCHAR

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = json.dumps(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = json.loads(value)
        return value


class MutableDict(Mutable, dict):
    @classmethod
    def coerce(cls, key, value):
        "Convert plain dictionaries to MutableDict."

        if not isinstance(value, MutableDict):
            if isinstance(value, dict):
                return MutableDict(value)

            # this call will raise ValueError
            return Mutable.coerce(key, value)
        else:
            return value

    def __setitem__(self, key, value):
        "Detect dictionary set events and emit change events."

        dict.__setitem__(self, key, value)
        self.changed()

    def __delitem__(self, key):
        "Detect dictionary del events and emit change events."

        dict.__delitem__(self, key)
        self.changed()

    def __getstate__(self):
        return dict(self)

    def __setstate__(self, state):
        self.update(state)



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('last_updated', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_last_updated', 'user', ['last_updated'], unique=True)
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('pinboard_videos', sa.JSONEncodedDict(), nullable=True),
    # sa.Column('pinboard_playlists', sa.JSONEncodedDict(), nullable=True),
    # sa.Column('pinboard_subscriptions', sa.JSONEncodedDict(), nullable=True),
    # sa.Column('youtube_videos', sa.JSONEncodedDict(), nullable=True),
    # sa.Column('youtube_playlists', sa.JSONEncodedDict(), nullable=True),
    sa.Column('pinboard_videos', MutableDict.as_mutable(JSONEncodedDict), nullable=True),
    sa.Column('pinboard_playlists', MutableDict.as_mutable(JSONEncodedDict), nullable=True),
    sa.Column('pinboard_subscriptions', MutableDict.as_mutable(JSONEncodedDict), nullable=True),
    sa.Column('youtube_videos', MutableDict.as_mutable(JSONEncodedDict), nullable=True),
    sa.Column('youtube_playlists', MutableDict.as_mutable(JSONEncodedDict), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'],),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_info_pinboard_playlists', 'info', ['pinboard_playlists'], unique=False)
    op.create_index('ix_info_pinboard_subscriptions', 'info', ['pinboard_subscriptions'], unique=False)
    op.create_index('ix_info_pinboard_videos', 'info', ['pinboard_videos'], unique=False)
    op.create_index('ix_info_youtube_playlists', 'info', ['youtube_playlists'], unique=False)
    op.create_index('ix_info_youtube_videos', 'info', ['youtube_videos'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_info_youtube_videos', table_name='info')
    op.drop_index('ix_info_youtube_playlists', table_name='info')
    op.drop_index('ix_info_pinboard_videos', table_name='info')
    op.drop_index('ix_info_pinboard_subscriptions', table_name='info')
    op.drop_index('ix_info_pinboard_playlists', table_name='info')
    op.drop_table('info')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_index('ix_user_last_updated', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
