"""empty message

Revision ID: 45bf06099bb7
Revises: None
Create Date: 2014-03-13 19:14:28.190584

"""

# revision identifiers, used by Alembic.
revision = '45bf06099bb7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
